app/models/__init__.py
from .user import User
from .post import Posts

app/models/post.py
from datetime import datetime

from app.extensions import db


class Posts(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    rid = db.Column(db.Integer, index=True, default=0)
    content = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    # Join "users" table
    uid = db.Column(db.Integer, db.ForeignKey('users.id'))

app/models/user.py
from app.extensions import db, login_manager
from flask_login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.INTEGER,primary_key=True)
    username = db.Column(db.String(32))
    password = db.Column(db.String(128))

    # add relationship model
    posts = db.relationship('Posts', backref='user', lazy='dynamic')


@login_manager.user_loader
def loader_user(user_id):
    return User.query.get(int(user_id))

app/forms/__init__.py
from .user import RegisterForm, LoginForm
from .posts import PostForm

app/forms/posts.py
from flask_wtf import  FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    content = TextAreaField('', render_kw={'placeholder':'Post new message......'},
                            validators=[DataRequired(),
                            Length(1, 128, message='post something')])
    submit = SubmitField('Publish')

app/forms/user.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Length, EqualTo

from app.models import User


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(),
                                                   Length(6, 14, message='The length must between 6-14')])
    password = PasswordField('Password', validators=[DataRequired(),
                                                     Length(6, 10, message='The length must between 6-10')])
    confirm = PasswordField('Confirm pwd', validators=[EqualTo('password',message='Password inconsistency')])

    submit = SubmitField('Register')

# username validation
# def validate_username(self, field):
#     if User.query.filter_by(username=field.data).first():
#         raise ValidationError('The Username has been used,please choose another one')


class LoginForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = StringField('password', validators=[DataRequired()])
    submit = SubmitField('Login')

app/__init__.py
from flask import Flask, render_template
from app.config import config
from app.extensions import config_extentions
from app.views import config_blueprint

# app = Flask(__name__)


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    config_extentions(app)
    config_blueprint(app)

    config_errorhandler(app)
    return app


def config_errorhandler(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('errors/404.html')

app/views/__init__.py
from .main import main
from .user import user

DEFAULT_BLUEPRINT = (
    (main, ''),
    (user, '/user')
)


def config_blueprint(app):
    for blue_print,url_prefix in DEFAULT_BLUEPRINT:
        app.register_blueprint(blue_print, url_prefix=url_prefix)

app/views/main.py
from flask import Blueprint, render_template, flash, url_for, redirect, request
from app.forms import PostForm
from app.models import Posts
from flask_login import current_user
from app.extensions import db

main = Blueprint('main',__name__)


@main.route('/', methods=['GET','POST'])
def index():
    form = PostForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            u = current_user._get_current_object()
            p = Posts(content=form.content.data, user=u)
            db.session.add(p)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('You need to login first')
            return redirect(url_for('user.login'))
    #read messages from db
    # posts = Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()).all()

    # get current page number
    page = request.args.get('page', 1, type=int)
    pagination = Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()).paginate(page, per_page=5, error_out=False)
    posts = pagination.items
    return render_template('main/index.html', form=form, posts=posts, pagination=pagination)

app/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for
from app.forms import RegisterForm, LoginForm
from app.models import User
from app.extensions import db
from flask_login import login_user, logout_user

user = Blueprint('user', __name__)


@user.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # create object
        u = User(username=form.username.data, password=form.password.data)
        # store in db
        db.session.add(u)
        db.session.commit()

        flash('URegistered successfully')
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)


@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None :
            flash('Invalid username or password')
            return redirect(url_for('user.login'))
        else:
            login_user(user)
            return redirect(url_for('main.index'))
    return render_template('user/login.html', form=form)


@user.route('/logout/')
def logout():
    logout_user()
    flash('Logout')
    return redirect(url_for('main.index'))

app/templates/common/base.html
{% extends 'bootstrap/base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} Job {% endblock %}

{% block navbar %}

<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{url_for('main.index')}}">JOB</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">POST1</a></li>
        <li><a href="#">POST2</a></li>
      </ul>


      <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
              <li><a href="{{url_for('user.logout')}}">Logout</a></li>
          {% else %}
              <li><a href="{{url_for('user.login')}}">Login</a></li>
              <li><a href="{{url_for('user.register')}}">Register</a></li>
          {% endif %}

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% endblock %}

{% block content %}
<div class="container">
{#    Welcome#}
   {% block page_content %}Welcome
   {% endblock %}

</div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}

{% endblock %}

app/templates/common/macro.html
{% macro pagination_show(pagination, endpoint) %}

    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li {% if not pagination.has_prev %}class="disabled"> {% endif %}
                <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs)}}{% else %} {% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

        {% for p in pagination.iter_pages() %}
            {% if p %}
                <li {% if pagination.page == p %}class="active"{% endif %}><a href="{{ url_for(endpoint, page=p, **kwargs)}}">{{ p }}</a></li>
            {% else %}
                <li><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}

            <li {% if not pagination.has_next %}class="disabled"> {% endif %}
                <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs)}}{% else %} {% endif %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>


{% endmacro %}

app/templates/main/index.html
{% extends 'common/base.html' %}

{% from 'common/macro.html' import pagination_show %}

{% block title %} Home {% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}

{% for p in posts %}
    <hr style="margin-top: 10px; margin-bottom: 10px;"/>
    <div class="media">
        <div class="media-left">
            <a href="#">
                <img class="media-object" src="..." alt="...">
            </a>
        </div>
        <div class="media-body">
            <div style="float: right;">{{ moment(p.timestamp).fromNow() }}</div>
            <h4 class="media-heading">{{ p.user.username }}</h4>
            {{ p.content }}
        </div>
    </div>


{% endfor %}
 <hr/>

{{ pagination_show(pagination, 'main.index') }}

{% endblock %}

app/templates/user/login.html
{% extends 'common/base.html' %}

{% block title %}Login{% endblock %}
{% block page_content %}

<div class="container">
   {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/user/register.html
{% extends 'common/base.html' %}

{% block title %}Register{% endblock %}
{% block page_content %}

<div class="container">
   {{ wtf.quick_form(form) }}
</div>

{% endblock %}